- name: replace source repo to speed up the download speed
  copy: src=sources.list dest=/etc/apt/sources.list

- name: install xvfb
  apt: name={{item}} state=present install_recommends=no update_cache=true
  with_items:
    - xvfb
    - firefox
